# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  host: localhost
  port: 3306
  username: bmason_db
  password: password
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bmason_dev

test:
  <<: *default
  database: bmason_test

production:
  <<: *default
  database: bmason_prod
